### ISSUE TITLE
Add README for the project

### ISSUE THREAD

**Issue by mrp97** [Sherinpour/CRUD-project#3]
There is a functionality in Github that you can add to a README file to repo to communicate important information about your project.

You can read more about it here: 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes

It would be great if you add a README to this repository and:
- Describe the project in a paragraph.
- Put a screenshot of the project as demo purpose.
- Put the Github Page link to see the live functionality of the project.

**Comment by Sherinpour** [comment]
I did it.🙂
